[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1
hook_source = '''
  if filereadable(expand('$DOTVIM/vimrc.neocomplete'))
    source $DOTVIM/vimrc.neocomplete
  endif
'''

[[plugins]]
repo = 'Shougo/neocomplcache'
if = '! has("lua")'
on_i = 1
hook_source = '''
  if filereadable(expand('$DOTVIM/vimrc.neocomplcache'))
    source $DOTVIM/vimrc.neocomplcache
  endif
'''

[[plugins]]
repo = 'moll/vim-node'
on_ft = 'javascript'

[[plugins]]
repo = 'mattn/jscomplete-vim'
on_ft = 'javascript'

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
on_ft = 'javascript'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
